[package]
name = "primera-prueba"
version = "0.1.0"
edition = "2021"
[[bin]]
path="src/primer-principal.rs"
name = "primer-prueba"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"